avatar: https://kira.host/assets/Pictures/Others/20220922230447.jpg # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: https://kira.host/assets/Pictures/Others/-f0d5cc34c6e5aa7_compressed.jpg
    width: 1280
    height: 720
favicon:
    href: https://kira.host/assets/Pictures/Others/116359b4ccf19917.jpg # 网站图标
    type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 附加图标库 使用说明：https://kira.host/hexo/config/icon.html
# iconlib: //at.alicdn.com/t/font_3299330_el19bsi97h8.css

cdn: # 这里可以修改站点使用的库的CDN
    gitalk:
        css: https://unpkg.com/gitalk@latest/dist/gitalk.css
        js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
    giscus:
        js: https://giscus.app/client.js

# beian: 赣ICP备2021007955号-3 # 备案号（选填，别往你们网站上挂我的备案号！！！）

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /archive.html
        - icon-container
    关于本人:
        - /about.html
        - icon-user
    我的朋友:
        - /friends.html
        - icon-team

widgets:
    - social
    - category
    - tagcloud
    - archive

maxTagcloud: 0 # 标签云组件显示的标签数量，0 表示不限制

social:
    QQ:
        - tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=<去掉尖括号后填上你的QQ号>&website=www.oicqzone.com
        - icon-QQ
        - rgb(49, 174, 255)
        - rgba(49, 174, 255, .1)
    哔哩哔哩:
        - https://space.bilibili.com/<改成你的B站uid>
        - icon-bilibili
        - rgb(231, 106, 141)
        - rgba(231, 106, 141, .15)
    GitHub:
        - https://github.com/<你的github id>/
        - icon-github
        - rgb(25, 23, 23)
        - rgba(25, 23, 23, .15)
    Gitee:
        - https://gitee.com/<你的gitee id>
        - icon-gitee
        - rgb(165, 15, 15)
        - rgba(165, 15, 15, .15)

color: # 配色方案，从first到seventh为优先级为1-7的颜色，默认为彩虹配色
    first: # 同时作为主题色
        r: 49
        g: 174
        b: 255
    second:
        r: 255
        g: 78
        b: 106
    third:
        r: 255
        g: 185
        b: 0
    fourth:
        r: 51
        g: 213
        b: 122
    fifth:
        r: 0
        g: 219
        b: 255
    sixth:
        r: 255
        g: 69
        b: 0
    seventh:
        r: 144
        g: 144
        b: 255

# 评论区
gitalk:
    active: false # 是否启用 gitalk
    admin: -your github username- # 拥有对该repo进行操作的 GitHub username
    owner: -your github username- # 持有该 repo 的 GitHub username
    repo: -issue repo name- # 存放评论的 issue 所在的 repo
    clientID: -id- # GitHub Client ID
    clientSecret: -key- # GitHub Client Secret
    title: '' # Gitalk Issue Title
# 你们不要在这里填我的 giscus 配置项，不然你们博客下的评论会全部跑到我的仓库下面……
# https://giscus.app/zh-CN 可以在这个网站上手动选择配置填到下方对应位置
giscus:
    active: true # 是否启用 giscus
    repo: -your github username-/-your giscus repo- # 存放评论的 discus 所在的 repo
    repoID: -your giscus repo ID- # GitHub repo ID
    category: Announcements # 选择新 discussions 所在的分类
    categoryID: -giscus category id- # 分类 ID
    mapping: pathname # pathname, url, title, og:title, specific, number
    # term: # abc 123 # specific | number
    theme: light
    lang: en

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'
copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

# 自定义侧边栏尾部内容
sidebar: ''

# 自定义样式
# customStyles:
#     - style
#     - custom

# 友链配置
friends:
    # - avatar: <友链缩略图>
    #   link: <跳转连接>
    #   name: <名称>

# 可复制的代码块
copyableCodeblock: true
